import type { Metadata } from 'next'
import { Noto_Sans, Noto_Serif_KR } from 'next/font/google'
import './globals.css'
import Providers from './_providers'

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
})

const notoSerifKr = Noto_Serif_KR({
  variable: '--font-noto-serif-kr',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} ${notoSerifKr.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
